-- Généré par Oracle SQL Developer Data Modeler 4.1.3.901
--   à :        2016-10-05 17:37:43 EDT
--   site :      Oracle Database 12c
--   type :      Oracle Database 12c


--- Create a database user named CRMS and run this script connected as that user ---

CREATE TABLE ACCUSE
  (
    ACCUSE_ID VARCHAR2 (20) NOT NULL ,
    PV        VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE ACCUSE ADD CONSTRAINT ACCUSE_PK PRIMARY KEY ( ACCUSE_ID ) ;


CREATE TABLE CAS_CRIMINEL
  (
    CAS_ID            VARCHAR2 (20) NOT NULL ,
    CRIMINEL_ID       VARCHAR2 (20) NOT NULL ,
    CRIME_ID          VARCHAR2 (20) NOT NULL ,
    COURS_JUSTICE     VARCHAR2 (100) ,
    DATE_CONDAMNATION DATE
  ) ;
ALTER TABLE CAS_CRIMINEL ADD CONSTRAINT CRIMINEL_PKv2 PRIMARY KEY ( CRIMINEL_ID ) ;


CREATE TABLE CRIMINEL
  (
    CRIMINEL_ID   VARCHAR2 (20) NOT NULL ,
    COURS_JUSTICE VARCHAR2 (50)
  ) ;
ALTER TABLE CRIMINEL ADD CONSTRAINT CRIMINEL_PK PRIMARY KEY ( CRIMINEL_ID ) ;


CREATE TABLE DECLARATION
  (
    CAS_ID                VARCHAR2 (20) NOT NULL ,
    DECLARATION_PLAIGNANT VARCHAR2 (5000) ,
    DECLARATION_VICTIME   VARCHAR2 (5000) ,
    DECLARATION_ACCUSE    VARCHAR2 (5000)
  ) ;


CREATE TABLE OFFICIER
  (
    OFFICER_ID    VARCHAR2 (20) NOT NULL ,
    POSTE_ID      VARCHAR2 (20) NOT NULL ,
    GRADE         VARCHAR2 (20) ,
    NIVEAU_ACCESS INTEGER
  ) ;
ALTER TABLE OFFICIER ADD CONSTRAINT OFFICIER_PK PRIMARY KEY ( OFFICER_ID ) ;


CREATE TABLE PERSONNE
  (
    PERSON_ID VARCHAR2 (20) NOT NULL ,
    NOM       VARCHAR2 (500) ,
    PRENOM    VARCHAR2 (200) ,
    PHOTO BLOB ,
    DATE_NAISS     DATE ,
    SEXE           CHAR (1) ,
    ADRESSE        VARCHAR2 (500) ,
    REGION_ORIGINE VARCHAR2 (20) ,
    CNI            VARCHAR2 (20) ,
    PHONE_NUMBER   VARCHAR2 (15) ,
    EMAIL          VARCHAR2 (100)
  ) ;
ALTER TABLE PERSONNE ADD CONSTRAINT CRIMINELv1_PK PRIMARY KEY ( PERSON_ID ) ;


CREATE TABLE PLAIGNANT
  (
    PLAIGNANT_ID VARCHAR2 (20) NOT NULL ,
    PV           VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE PLAIGNANT ADD CONSTRAINT PLAIGNANT_PK PRIMARY KEY ( PLAIGNANT_ID ) ;


CREATE TABLE PLAINTE
  (
    CAS_ID                VARCHAR2 (20) NOT NULL ,
    OFFICIER_RECEVEUR     VARCHAR2 (20) NOT NULL ,
    NOM_CAS               VARCHAR2 (500) ,
    LOI_CONCERNE          VARCHAR2 (1000) ,
    STATUS_CAS            VARCHAR2 (20) ,
    MOMENT_INCIDENT       TIMESTAMP ,
    LIEU_INCIDENT         VARCHAR2 (500) ,
    DESCRIPTION           VARCHAR2 (1000) ,
    MOMENT_ENREGISTREMENT TIMESTAMP ,
    PV_ID                 VARCHAR2 (20) ,
    RESULTAT              VARCHAR2 (50)
  ) ;
ALTER TABLE PLAINTE ADD CONSTRAINT CAS_PK PRIMARY KEY ( CAS_ID ) ;


CREATE TABLE POSTE
  (
    POSTE_ID      VARCHAR2 (20) NOT NULL ,
    CONTACT_POSTE VARCHAR2 (15) ,
    NOM_POSTE     VARCHAR2 (200) ,
    ADRESSE_POSTE VARCHAR2 (200) ,
    ZONE          VARCHAR2 (200)
  ) ;
ALTER TABLE POSTE ADD CONSTRAINT POSTE_PK PRIMARY KEY ( POSTE_ID ) ;


CREATE TABLE PV
  (
    PV_ID     VARCHAR2 (20) NOT NULL ,
    OFFICIER  VARCHAR2 (20) NOT NULL ,
    CAS_ID    VARCHAR2 (20) NOT NULL ,
    LIEU      VARCHAR2 (200) ,
    CONTENU   VARCHAR2 (5000) ,
    MOMENT_PV TIMESTAMP ,
    STATUS    VARCHAR2 (20) ,
    RAISON    VARCHAR2 (5000)
  ) ;
ALTER TABLE PV ADD CONSTRAINT PV_PK PRIMARY KEY ( PV_ID ) ;


CREATE TABLE TYPE_CRIME
  (
    TYPE_CRIM_ID VARCHAR2 (20) NOT NULL ,
    CRIME_NAME VARCHAR2 (500) NOT NULL ,
    DELIT      VARCHAR2 (500)
  ) ;
ALTER TABLE TYPE_CRIME ADD CONSTRAINT TYPE_CRIME_PK PRIMARY KEY ( TYPE_CRIM_ID ) ;


CREATE TABLE VICTIME
  (
    VICTIM_ID VARCHAR2 (20) NOT NULL ,
    PV        VARCHAR2 (20) NOT NULL
  ) ;
ALTER TABLE VICTIME ADD CONSTRAINT VICTIME_PK PRIMARY KEY ( VICTIM_ID ) ;


ALTER TABLE ACCUSE ADD CONSTRAINT ACCUSE_PERSONNE_FK FOREIGN KEY ( ACCUSE_ID ) REFERENCES PERSONNE ( PERSON_ID ) ;

ALTER TABLE ACCUSE ADD CONSTRAINT ACCUSE_PV_FK FOREIGN KEY ( PV ) REFERENCES PV ( PV_ID ) ;

ALTER TABLE CAS_CRIMINEL ADD CONSTRAINT CAS_CRIMINEL_CRIMINEL_FK FOREIGN KEY ( CRIMINEL_ID ) REFERENCES CRIMINEL ( CRIMINEL_ID ) ;

ALTER TABLE CAS_CRIMINEL ADD CONSTRAINT CAS_CRIMINEL_TYPE_CRIME_FK FOREIGN KEY ( CRIME_ID ) REFERENCES TYPE_CRIME ( TYPE_CRIM_ID ) ;

ALTER TABLE CRIMINEL ADD CONSTRAINT CRIMINEL_PERSONNE_FK FOREIGN KEY ( CRIMINEL_ID ) REFERENCES PERSONNE ( PERSON_ID ) ;

ALTER TABLE DECLARATION ADD CONSTRAINT DECLARATION_CAS_FK FOREIGN KEY ( CAS_ID ) REFERENCES PLAINTE ( CAS_ID ) ;

ALTER TABLE OFFICIER ADD CONSTRAINT OFFICIER_PERSONNE_FK FOREIGN KEY ( OFFICER_ID ) REFERENCES PERSONNE ( PERSON_ID ) ;

ALTER TABLE OFFICIER ADD CONSTRAINT OFFICIER_POSTE_FK FOREIGN KEY ( POSTE_ID ) REFERENCES POSTE ( POSTE_ID ) ;

ALTER TABLE PLAINTE ADD CONSTRAINT PLAINTE_OFFICIER_FK FOREIGN KEY ( OFFICIER_RECEVEUR ) REFERENCES OFFICIER ( OFFICER_ID ) ;

ALTER TABLE PV ADD CONSTRAINT PV_OFFICIER_FK FOREIGN KEY ( OFFICIER ) REFERENCES OFFICIER ( OFFICER_ID ) ;

ALTER TABLE PV ADD CONSTRAINT TABLE_10_CAS_FK FOREIGN KEY ( CAS_ID ) REFERENCES PLAINTE ( CAS_ID ) ;

ALTER TABLE PLAIGNANT ADD CONSTRAINT TABLE_18_PERSONNE_FK FOREIGN KEY ( PLAIGNANT_ID ) REFERENCES PERSONNE ( PERSON_ID ) ;

ALTER TABLE PLAIGNANT ADD CONSTRAINT TABLE_18_PV_FK FOREIGN KEY ( PV ) REFERENCES PV ( PV_ID ) ;

ALTER TABLE CAS_CRIMINEL ADD CONSTRAINT TABLE_5_CAS_FK FOREIGN KEY ( CAS_ID ) REFERENCES PLAINTE ( CAS_ID ) ;

ALTER TABLE TYPE_CRIME ADD CONSTRAINT TYPE_CRIME_TYPE_CRIME_FK FOREIGN KEY ( TYPE_CRIM_ID ) REFERENCES TYPE_CRIME ( TYPE_CRIM_ID ) ;

ALTER TABLE VICTIME ADD CONSTRAINT VICTIME_PERSONNE_FK FOREIGN KEY ( VICTIM_ID ) REFERENCES PERSONNE ( PERSON_ID ) ;

ALTER TABLE VICTIME ADD CONSTRAINT VICTIME_PV_FK FOREIGN KEY ( PV ) REFERENCES PV ( PV_ID ) ;


-- Rapport récapitulatif d'Oracle SQL Developer Data Modeler : 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             28
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- TSDP POLICY                              0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   2
-- WARNINGS                                 0
